language: cpp
compiler:
  - gcc
install:
  - sudo apt-get install libgtest-dev
  - "cd /usr/src/gtest && cmake CMakeLists.txt && make && cp *.a /usr/lib"

script:
  - cmake CMakeLists.txt
  - make
  - ./runTests
