language: cpp

compiler:
  - gcc

dist: trusty
sudo: true

addons:
  apt:
    sources:
#      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
      - george-edison55
    packages:
      - cmake
      - cmake-data

before_install:
  - sudo apt-get install -y libgtest-dev
  - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
  - "wget https://github.com/google/leveldb/archive/v1.19.tar.gz && tar -xzf v1.19.tar.gz && rm v1.19.tar.gz && mv leveldb-1.19 /tmp/leveldb && cd /tmp/leveldb && make && sudo cp --preserve=links out-static/libleveldb.* /usr/local/lib && sudo cp -r include/leveldb /usr/local/include && sudo ldconfig"
  - "wget https://curl.haxx.se/download/curl-7.50.3.tar.gz && tar -xzf curl-7.50.3.tar.gz && rm curl-7.50.3.tar.gz && cd curl-7.50.3 && ./buildconf && ./configure && make && sudo make install && cd .. && cd .."
  - "sudo apt-get update && sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CD642CC5FF33A4B1 && sudo add-apt-repository -y ppa:ben-collins/libjwt && sudo apt-get update && sudo apt-get install -y libjwt-dev && cd ~/build/7552-taller2-jobify/application-server
"

script:
  - cmake CMakeLists.txt
  - make
  - ./runTests

notifications:
  slack: 7552-taller2-jobify:k32z7mkadyW1xTdrFsEqsiGX
