language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data

before_install:
  - sudo apt-get install libgtest-dev
  - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
  - "cd leveldb-master && make && cd out-static && cp --preserve=links libleveldb.* /usr/local/lib && cd .. && cp -r include/leveldb /usr/local/include/ && ldconfig && cd .."

script:
  - cmake CMakeLists.txt
  - make
  - ./runTests
