#!/bin/bash
#validacion
if [ ! -e "$PWD/empty/run" ]; then echo "Tenes que correrlo desde la raiz del proyecto."; exit 2; fi;

#levantando contenedor
docker run -it -v "$PWD":"/home" -w "/home" -p 8000:8000 7552taller2jobify/empty $*
